packages:
  - package-1
  - package-2
  - package-3
  - package-4
  - package-5
  - package-6
  - package-7
  - package-8
  - package-9
  - package-10
  - package-11
onlyBuiltDependencies:
  - '@biomejs/biome'
